name: ElectricSheepCompanion
options:
  bundleIdPrefix: org.electricsheep
  deploymentTarget:
    macOS: "12.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"

targets:
  ElectricSheepCompanion:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.electricsheep.companion
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: ElectricSheepCompanion.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Menu bar only - no dock icon
        INFOPLIST_KEY_LSUIElement: YES
    entitlements:
      path: ElectricSheepCompanion.entitlements
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Electric Sheep Companion
        CFBundleName: Electric Sheep Companion
        CFBundleIdentifier: org.electricsheep.companion
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSUIElement: true
        LSMinimumSystemVersion: "12.0"
        NSHumanReadableCopyright: "Copyright 2024 Electric Sheep Project. GPL-2.0 License."
        NSPrincipalClass: NSApplication
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
